### ISSUE TITLE
The ability to open links in the default browser set by the user

### ISSUE THREAD

**Issue by n00b12345** [JGeek00/linkdy#15]
My default browser on Android is Firefox. However, the "system browser" option does not open the link from linkdy in Firefox, and opens it in Chrome instead.

It would be great if the user were able to select the default browser to open the links in.

(Thanks for making the app)

**Comment by JGeek00** [comment]
Yes, that's because when you disable the integrated browser, it uses a feature that Chrome has to open a link on a popup window that's easily closable. The links are not opened on the browser itself, that's why the prompt to choose the browser doesn't appear. But I can add a toggle on the settings to also disable this feature.

**Comment by JGeek00** [comment]
Added on v1.4.0.
