### ISSUE TITLE
[FR] Share option "Shared"

### ISSUE THREAD

**Issue by sokai** [JGeek00/linkdy#5]
Thank you for the new sharing feature, see #4 !

Additionally I would suggest the Linkding option "Share" ("Share this bookmark with other registered users and anonymous users.").

KR

**Comment by JGeek00** [comment]
It's already implemented. If you long press a bookmark, and then tap on the share options, there you have the option to share internally.

**Comment by rbtzn** [comment]
Hello, 
I think that it could be useful to have a share toggle button when we create a new bookmard instead of sharing it afterward :
![image](https://github.com/JGeek00/linkdy/assets/164404597/9a4cb6cc-8641-4f44-b1bf-3b74074ba3fe)

(Also it seems that the end of the form is a little bit cropped)

Thanks again for your work !

**Comment by JGeek00** [comment]
Added on v1.3.0.
